# Usa la imagen oficial de PostgreSQL
FROM postgres:latest

# Define las variables de entorno para PostgreSQL
ENV POSTGRES_DB sc_taller1
ENV POSTGRES_USER postgres_t1
ENV POSTGRES_PASSWORD Uniandes2025!